version: "3"

services:
  app:
    build: .
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
