version: "3"

services:
  app:
    build: .
    restart: always
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
